Add check in / check out endpoints
eleanorhealth/go-athenahealth pull request #101
Opened 2023-07-06 06:14 UTC by seantcanavan

1. Implement `CancelCheckInAppointment`
2. Implement `CheckInAppointment`
3. Implement `CheckOutAppointment`
4. Implement `GetRequiredCheckInFields`
5. Implement `StartCheckInAppointment`

@dillonstreator @fterrag need advice on the breaking change to `BookAppointment`. I originally implemented the input arguments as integers however the API tends to return strings so to make functions more easily chainable I modified the input args to be strings. While integration testing I found myself needlessly converting a previous function's output string value to the `BookAppointment` function's integer parameter. If we want this in a separate PR or to be reverted just let me know.

Screenshot of copilotiq integration test success included.
![Screenshot from 2023-07-06 01-11-33](https://github.com/eleanorhealth/go-athenahealth/assets/6250751/4502981f-b581-4bfc-8e29-c69fb55be75c)

2023-07-09 17:11 UTC, fterrag commented
@seantcanavan I'm no longer at Eleanor Health, but @dillonstreator or @elliehastings will take care of you. Thanks for contributing to this project!

2023-07-10 20:19 UTC, seantcanavan commented on athenahealth/client.go
> +	StartCheckInAppointment(ctx context.Context, apptID string) error
no worries - i'm actually going to move GetRequiredFields to department.go since it's a department call

2023-07-10 20:39 UTC, seantcanavan commented
changes made

2023-07-14 18:41 UTC, seantcanavan commented
@dillonstreator @elliehastings any chance for a review here? got a few PRs lined up after this one. thanks! :heart:

2023-07-14 19:09 UTC, dillonstreator requested changes

2023-07-14 20:53 UTC, seantcanavan commented on athenahealth/insurance.go
> +	out := &ErrorMessageResponse{}
fixed!

2023-07-14 20:54 UTC, seantcanavan commented
@dillonstreator thanks! ready for re-review :nerd_face:

2023-07-17 14:16 UTC, merged